networks:
  tycho-network:
    name: tycho-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.default_bridge: 'false'
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.bridge.enable_ip_masquerade: 'true'
      com.docker.network.bridge.host_binding_ipv4: '0.0.0.0'
      com.docker.network.bridge.name: 'docker1'
      com.docker.network.driver.mtu: '1500'
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  rabbitmq:
    build:
      context: .
      dockerfile: DockerfileRabbit
    container_name: rabbitmq
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.97
    volumes:
      - ${DEFAULT_ROOT_FOLDER}/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    networks:
      tycho-network:
        ipv4_address: 172.18.0.98
    volumes:
      - ${DEFAULT_ROOT_FOLDER}/backup:/data/backup
      - ${DEFAULT_ROOT_FOLDER}/mongo/configdb:/data/configdb
      - ${DEFAULT_ROOT_FOLDER}/mongo/db:/data/db
      - ./conf/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    depends_on:
      - rabbitmq

  eureka:
    image: tycho-eureka:latest
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.95
    depends_on:
      - mongodb

  configserver:
    image: tycho-configserver:latest
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.91
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=native

  gateway:
    image: tycho-gateway:latest
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.90
    depends_on:
      - configserver
    env_file:
      - ${ENV_FILE}

  apache:
    image: tycho-apache:latest
    restart: unless-stopped
    ports:
      - '80:80'
    networks:
      tycho-network:
        ipv4_address: 172.18.0.99
    volumes:
      - ${DEFAULT_ROOT_FOLDER}/httpd:${DEFAULT_ROOT_FOLDER}/httpd

  tycho-auth-api:
    image: tycho-auth-api:latest
    container_name: tycho-auth-api
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.52
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
    env_file:
      - ${ENV_FILE}

  tycho-auth-front:
    image: tycho-auth-front:latest
    container_name: tycho-auth-front
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.55
    depends_on:
      - gateway

  tycho-admin-front:
    image: tycho-admin-front:latest
    container_name: tycho-admin-front
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.3
    depends_on:
      - gateway

  tycho-admin-api:
    image: tycho-admin-api:latest
    container_name: tycho-admin-api
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.2
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
    env_file:
      - ${ENV_FILE}

  tycho-catalog-front:
    image: tycho-catalog-front:latest
    container_name: tycho-catalog-front
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.31
    depends_on:
      - gateway

  tycho-catalog-api:
    image: tycho-catalog-api:latest
    container_name: tycho-catalog-api
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.30
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
    env_file:
      - ${ENV_FILE}

  tycho-revision-front:
    image: tycho-revision-front:latest
    container_name: tycho-revision-front
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.25
    depends_on:
      - gateway

  tycho-revision-api:
    image: tycho-revision-api:latest
    container_name: tycho-revision-api
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.24
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
    env_file:
      - ${ENV_FILE}

  tycho-functions-api:
    image: tycho-functions-api:latest
    container_name: tycho-functions-api
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.51
    volumes:
      - ${DEFAULT_ROOT_FOLDER}/httpd:${DEFAULT_ROOT_FOLDER}/httpd
      - ${DEFAULT_ROOT_FOLDER}/backup:${DEFAULT_ROOT_FOLDER}/backup
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
    env_file:
      - ${ENV_FILE}

  tycho-io-front:
    image: tycho-io-front:latest
    container_name: tycho-io-front
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.13
    depends_on:
      - gateway

  tycho-io-api:
    image: tycho-io-api:latest
    container_name: tycho-io-api
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.12
    volumes:
      - ${DEFAULT_ROOT_FOLDER}/httpd:${DEFAULT_ROOT_FOLDER}/httpd
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
    env_file:
      - ${ENV_FILE}

  tycho-comments-api:
    image: tycho-comments-api:latest
    container_name: tycho-comments-api
    restart: unless-stopped
    ports:
      - '8090:8080'
    networks:
      tycho-network:
        ipv4_address: 172.18.0.54
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
    env_file:
      - ${ENV_FILE}

  tycho-search-front:
    image: tycho-search-front:latest
    container_name: tycho-search-front
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.5
    depends_on:
      - gateway

  tycho-search-api:
    image: tycho-search-api:latest
    container_name: tycho-search-api
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.4
    volumes:
      - ${DEFAULT_ROOT_FOLDER}/httpd/upload:${DEFAULT_ROOT_FOLDER}/httpd/upload
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
    env_file:
      - ${ENV_FILE}

  tycho-parser-engine-api:
    image: tycho-parser-engine-api:latest
    container_name: tycho-parser-engine-api
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.53
    volumes:
      - ${DEFAULT_ROOT_FOLDER}/httpd:${DEFAULT_ROOT_FOLDER}/httpd
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
    env_file:
      - ${ENV_FILE}

  tycho-parser-front:
    image: tycho-parser-front:latest
    container_name: tycho-parser-front
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.7
    depends_on:
      - gateway

  tycho-parser-api:
    image: tycho-parser-api:latest
    container_name: tycho-parser-api
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.6
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
    env_file:
      - ${ENV_FILE}

  tycho-upload-api:
    image: tycho-upload-api:latest
    container_name: tycho-upload-api
    restart: unless-stopped
    networks:
      tycho-network:
        ipv4_address: 172.18.0.81
    volumes:
      - ${DEFAULT_ROOT_FOLDER}/httpd/upload:${DEFAULT_ROOT_FOLDER}/httpd/upload
      - /tmp:/tmp
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
    env_file:
      - ${ENV_FILE}
